### PR TITLE
Adding ref for postgres user

### PR DESCRIPTION
**Pull request by invicnaper**
adding the link of the repo foreman-ansible-postgres

### CODE REVIEW

**Comment by karras** [comment]
Thanks for the PR! I would rather not to have code distributed over several repositories. What do you think about creating a PR for your PGSQL role thus we can merge it?

**Comment by invicnaper** [comment]
Yes , but I will just PR the role, so you can keep mysql as the default adapter

**Comment by ytjohn** [comment]
I'm new to this project, but I do work with a good bit of ansible for private projects. I would suggest it might be worth looking at splitting up into separate roles. Maybe not today or next month, but down the road. The big reason is the rise in popularity of `ansible-galaxy`. 

When we start a project, we build a repository that contains playbooks, group_vars, ansible.cfg, maybe 1 or more Vagrantfiles, and and **requirements.yml**.   We might have a couple small roles within the directory, but the bigger roles are pulled in with ansible-galaxy (into a local ext_roles for testing, or default into /etc/ansible/roles). This saves us from having to build multiple copies of roles for things like apache, nginx, mysql, postgresql, etc.

For an example, take a look at the ansible roles maintained by [geerlingguy](https://galaxy.ansible.com/geerlingguy/). 

That being said, I am just extremely pleased with the work you have already put into a foreman-ansible playbook. I have been looking at ways to automate deployment of foreman and the current puppet-based installer has a lot of issues if a download times out. Once it gets past a certain point, it assumes that foreman is installed and won't re-run unless you wipe everything out.

**Comment by invicnaper** [comment]
I agree with @ytjohn, OpenStack-ansible are doing the same

**Comment by karras** [comment]
Project archived

**Pull request closed without merging**
